name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    env:
      CI: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
      timeout-minutes: 2
    - name: Install Chromium browser
      run: npx playwright install chromium --with-deps
      timeout-minutes: 2
    - name: Run tests
      run: "npx playwright test --reporter=list,html --project=chromium --trace=on"
      timeout-minutes: 3
      continue-on-error: true

    - name: Extract traces
      run: "./.github/extract_traces.sh"

    - name: Basic text input
      id: forms-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Basic text input
        setup-command: ''
        command: "./.github/find_trace.sh 'Nice job! You have greeted the page'"
        timeout: 1
        max-score: 5

    - name: Input without proper attributes
      id: forms-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Input without proper attributes
        setup-command: ''
        command: "./.github/find_trace.sh 'Done! But be careful, that phrase alone has crashed entire applications.'"
        timeout: 1
        max-score: 5

    - name: Reading values from the page
      id: forms-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Reading values from the page
        setup-command: ''
        command: "./.github/find_trace.sh 'You have successfully read a value from the page!'"
        timeout: 1
        max-score: 5

    - name: Radio buttons
      id: forms-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Radio buttons
        setup-command: ''
        command: "./.github/find_trace.sh '📻🎸🎵'"
        timeout: 1
        max-score: 5

    - name: Checkboxes
      id: forms-5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Checkboxes
        setup-command: ''
        command: "./.github/find_trace.sh 'Button-mashing detected.'"
        timeout: 1
        max-score: 5

    - name: Alerts and prompts
      id: forms-6
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Alerts and prompts
        setup-command: ''
        command: "./.github/find_trace.sh 'You have handled the prompt successfully!'"
        timeout: 1
        max-score: 5

    - name: Standard select element
      id: components-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Standard select element
        setup-command: ''
        command: "./.github/find_trace.sh 'You selected the correct option from a standard select element'"
        timeout: 1
        max-score: 5

    - name: Custom select element
      id: components-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Custom select element
        setup-command: ''
        command: "./.github/find_trace.sh 'You have selected the correct color using a custom select element'"
        timeout: 1
        max-score: 5

    - name: Standard date picker
      id: components-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Standard date picker
        setup-command: ''
        command: "./.github/find_trace.sh 'You have selected the correct date using a standard date picker'"
        timeout: 1
        max-score: 5

    - name: Custom date picker
      id: components-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Custom date picker
        setup-command: ''
        command: "./.github/find_trace.sh 'You have selected the correct date using a custom date picker'"
        timeout: 1
        max-score: 10

    - name: Mark todos as completed
      id: repetition-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Mark todos as completed
        setup-command: ''
        command: "./.github/find_trace.sh 'You literally checked all the boxes'"
        timeout: 1
        max-score: 5

    - name: Counter
      id: repetition-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Counter
        setup-command: ''
        command: "./.github/find_trace.sh 'If you keep clicking, I might start charging per press'"
        timeout: 1
        max-score: 5

    - name: Delayed appearance
      id: delays-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Delayed appearance
        setup-command: ''
        command: "./.github/find_trace.sh 'Nice job! Hello to you too!'"
        timeout: 1
        max-score: 5

    - name: Delayed enablement
      id: delays-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Delayed enablement
        setup-command: ''
        command: "./.github/find_trace.sh 'You must be a real tester!'"
        timeout: 1
        max-score: 5

    - name: Test page using different dates
      id: datetime-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test page using different dates
        setup-command: ''
        command: "./.github/find_trace.sh 'Time travel can be easy with the right tools'"
        timeout: 1
        max-score: 10

    - name: Dark mode
      id: responsive-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Dark mode
        setup-command: ''
        command: "./.github/find_trace.sh 'You have successfully switched between the modes'"
        timeout: 1
        max-score: 5

    - name: Responsive design
      id: responsive-2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Responsive design
        setup-command: ''
        command: "./.github/find_trace.sh 'You have successfully tested all supported screen sizes'"
        timeout: 1
        max-score: 10

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LOGIN-PAGE-1_RESULTS: "${{steps.login-page-1.outputs.result}}"
        LOGIN-PAGE-2_RESULTS: "${{steps.login-page-2.outputs.result}}"
        LOGIN-PAGE-3_RESULTS: "${{steps.login-page-3.outputs.result}}"
        LOGIN-PAGE-4_RESULTS: "${{steps.login-page-4.outputs.result}}"
        LOGIN-PAGE-5_RESULTS: "${{steps.login-page-5.outputs.result}}"
        LOGIN-PAGE-6_RESULTS: "${{steps.login-page-6.outputs.result}}"
        LOGIN-PAGE-7_RESULTS: "${{steps.login-page-7.outputs.result}}"

        REGISTER-PAGE-1_RESULTS: "${{steps.register-page-1.outputs.result}}"
        REGISTER-PAGE-2_RESULTS: "${{steps.register-page-2.outputs.result}}"
        REGISTER-PAGE-3_RESULTS: "${{steps.register-page-3.outputs.result}}"

      with:
        runners: login-page-1,login-page-2,login-page-3,login-page-4,login-page-5,login-page-6,login-page-7,register-page-1,register-page-2,register-page-3

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report
        retention-days: 30
